"""
Gemini client wrapper using google-genai SDK.
Defaults to Gemini Pro (gemini-2.5-pro) for high-grade analytical reasoning,
with native Pydantic structured output support and zero-cost test mockability.
"""

import logging
from typing import Any, Optional, Type, TypeVar

from google import genai
from google.genai import types
from pydantic import BaseModel

from src.config import get_gemini_api_key, get_gemini_model
from src.intelligence.prompts import SYSTEM_PROMPT

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)


class GeminiIntelligenceClient:
    """Client for generating fantasy football intelligence via Gemini Pro."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        mock_client: Optional[Any] = None,
    ) -> None:
        """Initialize the Gemini client.

        Args:
            api_key: Optional API key. If not provided, loaded from env via get_gemini_api_key().
            model: Optional model name. If not provided, loaded via get_gemini_model() (default: gemini-2.5-pro).
            mock_client: Optional mock client for testing without API keys.
        """
        self.model = model or get_gemini_model()
        self._mock_client = mock_client

        if mock_client is not None:
            self._client = mock_client
        else:
            resolved_key = api_key or get_gemini_api_key()
            self._client = genai.Client(api_key=resolved_key)

    def generate_structured(
        self,
        prompt: str,
        response_schema: Type[T],
        system_instruction: str = SYSTEM_PROMPT,
        temperature: float = 0.2,
    ) -> T:
        """Generate structured output adhering to a Pydantic schema using Gemini Pro.

        Args:
            prompt: Task-specific prompt and data payload.
            response_schema: The Pydantic model class to constrain the output.
            system_instruction: High-level analyst persona instructions.
            temperature: Sampling temperature (default 0.2 for deterministic analytical reasoning).

        Returns:
            An instance of response_schema populated with Gemini's structured response.
        """
        config = types.GenerateContentConfig(
            system_instruction=system_instruction,
            response_mime_type="application/json",
            response_schema=response_schema,
            temperature=temperature,
        )

        try:
            response = self._client.models.generate_content(
                model=self.model,
                contents=prompt,
                config=config,
            )

            # google-genai returns json in response.text
            raw_text = response.text or "{}"
            return response_schema.model_validate_json(raw_text)

        except Exception as e:
            logger.error(f"Gemini API request failed ({self.model}): {e}")
            raise

    def generate_text(
        self,
        prompt: str,
        system_instruction: str = SYSTEM_PROMPT,
        temperature: float = 0.3,
    ) -> str:
        """Generate unstructured text analysis.

        Args:
            prompt: The user prompt.
            system_instruction: System prompt.
            temperature: Sampling temperature.

        Returns:
            The raw text generated by the model.
        """
        config = types.GenerateContentConfig(
            system_instruction=system_instruction,
            temperature=temperature,
        )

        try:
            response = self._client.models.generate_content(
                model=self.model,
                contents=prompt,
                config=config,
            )
            return response.text or ""
        except Exception as e:
            logger.error(f"Gemini text generation failed ({self.model}): {e}")
            raise
